### ISSUE TITLE
Deploy Error: ReferenceError: x is not defined 

### ISSUE THREAD

**Issue by loretoparisi** [ParsePlatform/parse-cli#46]
I run into this issue

 
```javascript
Finished uploading files 

ReferenceError: x is not defined 

    at app.js:1:1 

    at main.js:1:1
```

when trying to deploy. I had an old app structure (<2.2.2), but I migrated to the new structure.

The current parse version is

```javascript
Already using the latest cli version: 3.0.1
```

Even if I can see a success message, I do not see the version uploaded to the cloud, since I do not find the new release:

```shell
macbookproloreto:test_cloud_code admin$ parse releases


Name                            Description                     Date

v241                            No release notes given          2015-07-12T19:24:27.153Z

 

v242                            No release notes given          2015-07-12T19:35:19.336Z
```

These are all old releases, not the latest one, as the upload script was interrupted due to the exception, and wrote the SUCCESS message anyways, but failing actually.

**Comment by loretoparisi** [comment]
Doh, it was a classical "type error" due to entering the char "x" in the main.js file no one knows why!
